### ISSUE TITLE
java.lang.IllegalStateException: Multiple renderer media clocks enabled

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#107]
01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: playerFailed [119.49]
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: com.google.android.exoplayer2.ExoPlaybackException
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:1372)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayingPeriodHolder(ExoPlayerImplInternal.java:1344)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1274)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:331)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:100)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at android.os.Looper.loop(Looper.java:148)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:61)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
	01-07 14:50:01.277 25153 25153 E ie.macinnes.tvheadend.player.EventLogger: 	... 8 more

**Comment by kiall** [comment]
This is caused by having multiple renderers of a single type selected, e.g. here we have 2 audio renderers. I'm unsure why we see this...

	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: videoDisabled [45.22]
	02-20 13:09:34.305 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspDataSource: New HtspDataSource instantiated
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: audioDisabled [45.22]
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: loading [false]
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onPlayerStateChanged: 1 (0)
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying video is unavailable, reason: 0
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying video is unavailable, reason: 0
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: state [45.22, true, I]
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onPlayerStateChanged: 2 (0)
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying video is unavailable, reason: 3
	02-20 13:09:34.305 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: state [45.22, true, B]
	02-20 13:09:34.310 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: sourceInfo [periodCount=1, windowCount=1
	02-20 13:09:34.310 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   period [?]
	02-20 13:09:34.310 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   window [?, false, false]
	02-20 13:09:34.310 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: ]
	02-20 13:09:34.330 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: New HtspExtractor instantiated
	02-20 13:09:34.335 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: loading [true]
	02-20 13:09:34.380 8404-8418/ie.macinnes.tvheadend W/art: Suspending all threads took: 5.799ms
	02-20 13:09:34.450 8404-8413/ie.macinnes.tvheadend W/art: Suspending all threads took: 34.585ms
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetStreamVolume: 0.0 (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetStreamVolume: 0.0 (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetStreamVolume: 0.0 (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.480 8404-8418/ie.macinnes.tvheadend I/art: Background sticky concurrent mark sweep GC freed 39582(2MB) AllocSpace objects, 21(5MB) LOS objects, 0% free, 73MB/73MB, paused 7.120ms total 141.655ms
	02-20 13:09:34.500 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetStreamVolume: 0.0 (0)
	02-20 13:09:34.500 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.500 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:34.915 8404-8418/ie.macinnes.tvheadend I/art: Background partial concurrent mark sweep GC freed 14412(617KB) AllocSpace objects, 7(17MB) LOS objects, 21% free, 57MB/73MB, paused 4.481ms total 401.960ms
	02-20 13:09:35.395 8404-24266/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.player.HtspExtractor: Handling Subscription Start
	02-20 13:09:35.395 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: Creating StreamReader for TEXTSUB stream at index 5
	02-20 13:09:35.395 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: Creating StreamReader for H264 stream at index 1
	02-20 13:09:35.395 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: Creating StreamReader for MPEG2AUDIO stream at index 2
	02-20 13:09:35.400 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: Creating StreamReader for TELETEXT stream at index 4
	02-20 13:09:35.400 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: Creating StreamReader for MPEG2AUDIO stream at index 3
	02-20 13:09:35.400 8404-24266/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.HtspExtractor: All streams have now been handled
	02-20 13:09:35.400 8404-22842/ie.macinnes.tvheadend D/MediaCodecInfo: NoSupport [channelCount.support, 2] [OMX.MTK.AUDIO.DECODER.DSPMP1, audio/mpeg-L2] [SVP-DTV15, BRAVIA 4K 2015, Sony, 22]
	02-20 13:09:35.405 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: sourceInfo [periodCount=1, windowCount=1
	02-20 13:09:35.405 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   period [?]
	02-20 13:09:35.405 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   window [?, false, false]
	02-20 13:09:35.405 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: ]
	02-20 13:09:35.410 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.TvheadendTrackSelector: TrackSelector selectVideoTrack
	02-20 13:09:35.410 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.TvheadendTrackSelector: TrackSelector selectAudioTrack
	02-20 13:09:35.410 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.TvheadendTrackSelector: TrackSelector selectAudioTrack
	02-20 13:09:35.410 8404-22842/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.TvheadendTrackSelector: TrackSelector selectTextTrack
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onTracksChanged: 4 (0)
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing trackGroup: 0
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing track: 0
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.ExoPlayerUtils: Processing track: 1440x1080, id:1
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing trackGroup: 1
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing track: 0
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.ExoPlayerUtils: Processing track: eng, 2ch, 48000Hz, id:2
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing trackGroup: 2
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing track: 0
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.ExoPlayerUtils: Processing track: nar, 1ch, 48000Hz, id:3
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing trackGroup: 3
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Processing track: 0
	02-20 13:09:35.410 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.ExoPlayerUtils: Processing track: eng, id:5
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying video track selected: 1
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying audio track selected: 3
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Notifying audio track selected: 2
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: Tracks [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   Renderer:0 [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     Group:0, adaptive_supported=N/A [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:       [X] Track:0, id=1, mimeType=video/avc, containerMimeType=null, res=1440x1080, supported=YES
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     ]
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   ]
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   Renderer:1 [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     Group:0, adaptive_supported=N/A [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:       [X] Track:0, id=3, mimeType=audio/mpeg-L2, containerMimeType=null, channels=1, sample_rate=48000, language=nar, supported=YES
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     ]
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   ]
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   Renderer:2 [
	02-20 13:09:35.415 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     Group:0, adaptive_supported=N/A [
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:       [X] Track:0, id=2, mimeType=audio/mpeg-L2, containerMimeType=null, channels=2, sample_rate=48000, language=eng, supported=YES
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     ]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   ]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   Renderer:3 [
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     Group:0, adaptive_supported=N/A [
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:       [ ] Track:0, id=5, mimeType=application/x-subrip, containerMimeType=null, language=eng, supported=YES
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:     ]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger:   ]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: ]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: videoEnabled [46.34]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: audioEnabled [46.34]
	02-20 13:09:35.430 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: audioEnabled [46.34]
	02-20 13:09:35.435 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:35.435 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:35.440 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.ExoPlayerSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:35.440 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.tvinput.BaseSession: Session onSetCaptionEnabled: false (0)
	02-20 13:09:35.445 8404-22842/ie.macinnes.tvheadend E/ExoPlayerImplInternal: Renderer error.
	                                                                             com.google.android.exoplayer2.ExoPlaybackException
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:1376)
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayingPeriodHolder(ExoPlayerImplInternal.java:1346)
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1274)
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
	                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
	                                                                                 at android.os.Looper.loop(Looper.java:135)
	                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
	                                                                                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
	                                                                              Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:1376) 
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayingPeriodHolder(ExoPlayerImplInternal.java:1346) 
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1274) 
	                                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316) 
	                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98) 
	                                                                                 at android.os.Looper.loop(Looper.java:135) 
	                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61) 
	                                                                                 at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
	02-20 13:09:35.445 8404-8404/ie.macinnes.tvheadend E/ie.macinnes.tvheadend.player.EventLogger: playerFailed [46.36]
	                                                                                               com.google.android.exoplayer2.ExoPlaybackException
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:1376)
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayingPeriodHolder(ExoPlayerImplInternal.java:1346)
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1274)
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
	                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
	                                                                                                   at android.os.Looper.loop(Looper.java:135)
	                                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
	                                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
	                                                                                                Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:1376) 
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayingPeriodHolder(ExoPlayerImplInternal.java:1346) 
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1274) 
	                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316) 
	                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
	                                                                                                   at android.os.Looper.loop(Looper.java:135) 
	                                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
	                                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
	02-20 13:09:35.450 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: videoDisabled [46.36]
	02-20 13:09:35.450 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: audioDisabled [46.36]
	02-20 13:09:35.450 8404-8404/ie.macinnes.tvheadend D/ie.macinnes.tvheadend.player.EventLogger: audioDisabled [46.36]
