### ISSUE TITLE
Attempt to invoke virtual method .. SocketChannel.register

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#116]
01-20 11:11:59.551 21958-21958/? I/art: Late-enabling -Xcheck:jni
    01-20 11:11:59.567 21958-21964/? E/art: Failed sending reply to debugger: Broken pipe
    01-20 11:11:59.567 21958-21964/? I/art: Debugger is no longer active
    01-20 11:11:59.597 21958-21958/? I/ie.macinnes.tvheadend.migrate.MigrateUtils: Migrate from 79 to 79
    01-20 11:11:59.675 21958-21976/? I/OpenGLRenderer: Initialized EGL, version 1.4
    01-20 11:12:21.001 21958-21958/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.sync.EpgSyncService: Starting EPG Sync Service
    01-20 11:12:21.009 21958-22332/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: Opening HTSP Connection
    01-20 11:12:23.019 21958-22332/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: HTSP Connected
    01-20 11:12:23.034 21958-22332/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: HTSP Ready
    01-20 11:12:23.050 21958-22331/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.sync.EpgSyncTask: Enabling Async Metadata. Last Update: 1484910715, EPG max time: 1484914343
    01-20 11:12:52.702 21958-21964/ie.macinnes.tvheadend W/art: Suspending all threads took: 8.349ms
    01-20 11:12:55.214 21958-22331/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.sync.EpgSyncTask: Initial sync completed
    01-20 11:12:55.218 21958-22331/ie.macinnes.tvheadend E/ie.macinnes.htsp.tasks.GetFileTask: Error handling a GetFileTask message
    01-20 11:12:55.219 21958-22331/ie.macinnes.tvheadend W/ie.macinnes.tvheadend.sync.EpgSyncTask: Failed to fetch logo for content://android.media.tv/channel/2433. This usually means TVHeadend doesn't have a logo for this channel.
    01-20 11:12:55.220 21958-22331/ie.macinnes.tvheadend E/ie.macinnes.htsp.tasks.GetFileTask: Error handling a GetFileTask message
    01-20 11:12:55.225 21958-22331/ie.macinnes.tvheadend W/ie.macinnes.tvheadend.sync.EpgSyncTask: Failed to fetch logo for content://android.media.tv/channel/2442. This usually means TVHeadend doesn't have a logo for this channel.
    01-20 11:12:55.236 21958-22331/ie.macinnes.tvheadend E/ie.macinnes.htsp.tasks.GetFileTask: Error handling a GetFileTask message
    01-20 11:12:55.236 21958-22331/ie.macinnes.tvheadend W/ie.macinnes.tvheadend.sync.EpgSyncTask: Failed to fetch logo for content://android.media.tv/channel/2456. This usually means TVHeadend doesn't have a logo for this channel.
    01-20 11:12:55.246 21958-22332/ie.macinnes.tvheadend E/ie.macinnes.htsp.Connection: Something failed - shutting down
                                                                                        java.nio.channels.ClosedChannelException
                                                                                            at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:418)
                                                                                            at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:357)
                                                                                            at ie.macinnes.htsp.Connection.processWritableSelectionKey(Connection.java:456)
                                                                                            at ie.macinnes.htsp.Connection.run(Connection.java:153)
                                                                                            at java.lang.Thread.run(Thread.java:818)
    01-20 11:12:55.246 21958-22332/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: Connection already closed, ignoring close request
    01-20 11:12:55.248 21958-21958/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.sync.EpgSyncService: Starting EPG Sync Service
    01-20 11:12:55.248 21958-22331/ie.macinnes.tvheadend E/AndroidRuntime: FATAL EXCEPTION: EpgSyncService Handler Thread
                                                                           Process: ie.macinnes.tvheadend, PID: 21958
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.channels.SelectionKey java.nio.channels.SocketChannel.register(java.nio.channels.Selector, int)' on a null object reference
                                                                               at ie.macinnes.htsp.Connection.sendMessage(Connection.java:330)
                                                                               at ie.macinnes.htsp.Connection.sendMessage(Connection.java:341)
                                                                               at ie.macinnes.htsp.tasks.GetFileTask.sendFileRead(GetFileTask.java:152)
                                                                               at ie.macinnes.htsp.tasks.GetFileTask.sendFileRead(GetFileTask.java:135)
                                                                               at ie.macinnes.htsp.tasks.GetFileTask.onMessage(GetFileTask.java:101)
                                                                               at ie.macinnes.htsp.Connection$3.run(Connection.java:437)
                                                                               at android.os.Handler.handleCallback(Handler.java:742)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:97)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
    01-20 11:12:55.261 21958-22839/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: Opening HTSP Connection
    01-20 11:12:57.266 21958-22839/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: HTSP Connected
    01-20 11:12:57.281 21958-22839/ie.macinnes.tvheadend I/ie.macinnes.htsp.Connection: HTSP Ready
    01-20 11:12:57.974 21958-22837/ie.macinnes.tvheadend I/ie.macinnes.tvheadend.sync.EpgSyncTask: Enabling Async Metadata. Last Update: 1484910775, EPG max time: 1484953977

**Comment by kiall** [comment]
Nope, not fixed and still happening:

	0	--------- beginning of main
	1	01-20 15:08:23.950 I/ie.macinnes.tvheadend.sync.EpgSyncTask( 1827): Initial sync completed
	2	01-20 15:08:23.968 I/ie.macinnes.tvheadend.sync.EpgSyncService( 1827): Stopping EPG Sync Service
	3	01-20 15:08:23.968 I/ie.macinnes.htsp.Connection( 1827): Closing HTSP Connection, End State: 0
	4	01-20 15:08:23.968 I/ie.macinnes.htsp.Connection( 1827): Calling SocketChannel close
	5	01-20 15:08:23.968 W/ie.macinnes.htsp.Connection( 1827): Calling Selector close
	6	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): Something failed - shutting down
	7	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): java.nio.channels.ClosedChannelException
	8	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:268)
	9	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:477)
	10	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): at ie.macinnes.htsp.Connection.processWritableSelectionKey(Connection.java:466)
	11	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): at ie.macinnes.htsp.Connection.run(Connection.java:153)
	12	01-20 15:08:23.980 E/ie.macinnes.htsp.Connection( 1827): at java.lang.Thread.run(Thread.java:761)
	13	01-20 15:08:23.992 I/ie.macinnes.htsp.Connection( 1827): Connection already closed, ignoring close request
	14	01-20 15:08:23.993 E/ACRA ( 1827): ACRA caught a NullPointerException for ie.macinnes.tvheadend
	15	01-20 15:08:23.993 E/ACRA ( 1827): java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.channels.SelectionKey java.nio.channels.SelectableChannel.register(java.nio.channels.Selector, int)' on a null object reference
	16	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.Connection.sendMessage(Connection.java:340)
	17	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.Connection.sendMessage(Connection.java:351)
	18	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.tasks.GetFileTask.sendFileRead(GetFileTask.java:160)
	19	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.tasks.GetFileTask.sendFileRead(GetFileTask.java:142)
	20	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.tasks.GetFileTask.onMessage(GetFileTask.java:102)
	21	01-20 15:08:23.993 E/ACRA ( 1827): at ie.macinnes.htsp.Connection$3.run(Connection.java:447)
	22	01-20 15:08:23.993 E/ACRA ( 1827): at android.os.Handler.handleCallback(Handler.java:751)
	23	01-20 15:08:23.993 E/ACRA ( 1827): at android.os.Handler.dispatchMessage(Handler.java:95)
	24	01-20 15:08:23.993 E/ACRA ( 1827): at android.os.Looper.loop(Looper.java:154)
	25	01-20 15:08:23.993 E/ACRA ( 1827): at android.os.HandlerThread.run(HandlerThread.java:61)
	26	01-20 15:08:24.039 I/ie.macinnes.tvheadend.sync.EpgSyncService( 1827): Starting EPG Sync Service
	27	01-20 15:08:24.053 I/ie.macinnes.htsp.Connection( 1827): Opening HTSP Connection

**Comment by kiall** [comment]
The new HTSP lib just merged will have fixed this (the original code is gone)..
