### ISSUE TITLE
Crash and black screen if TVHeadend server is not reachable

### ISSUE THREAD

**Issue by cyberjacob** [kiall/android-tvheadend#133]
If the tvheadend server is not reachable (for example, if it has crashed), the client crashes and leaves the user at a black screen with no information or user-friendly error message. Changing to another channel restarts the client, however this takes some time. Not really a bug, but it would be useful to have some kind of error message displayed to the user.

    02-21 10:39:57.414 17382-17412/ie.macinnes.tvheadend I/HtspConnection: Opening HTSP Connection
    02-21 10:39:57.430 17382-17412/ie.macinnes.tvheadend E/HtspConnection: Something failed - shutting down
                                                                           java.net.ConnectException: failed to connect to tvstreaming/172.16.42.42 (port 9982): isConnected failed: ECONNREFUSED (Connection refused)
                                                                               at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                                               at java.nio.SocketChannelImpl.finishConnect(SocketChannelImpl.java:277)
                                                                               at ie.macinnes.htsp.HtspConnection.processConnectableSelectionKey(HtspConnection.java:277)
                                                                               at ie.macinnes.htsp.HtspConnection.run(HtspConnection.java:216)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                               at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                               at java.nio.SocketChannelImpl.finishConnect(SocketChannelImpl.java:277) 
                                                                               at ie.macinnes.htsp.HtspConnection.processConnectableSelectionKey(HtspConnection.java:277) 
                                                                               at ie.macinnes.htsp.HtspConnection.run(HtspConnection.java:216) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
    02-21 10:39:57.430 17382-17412/? I/HtspConnection: Closing HTSP Connection
    02-21 10:39:57.432 17382-17412/? W/SimpleHtspConnection: HTSP Connection failed, reconnecting
    02-21 10:39:57.432 17382-17412/? E/AndroidRuntime: FATAL EXCEPTION: Thread-990
                                                       Process: ie.macinnes.tvheadend, PID: 17382
                                                       java.lang.IllegalThreadStateException: Thread already started
                                                           at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                           at java.lang.Thread.start(Thread.java:1059)
                                                           at ie.macinnes.htsp.SimpleHtspConnection.start(SimpleHtspConnection.java:59)
                                                           at ie.macinnes.htsp.SimpleHtspConnection.onConnectionStateChange(SimpleHtspConnection.java:124)
                                                           at ie.macinnes.htsp.HtspConnection.setState(HtspConnection.java:384)
                                                           at ie.macinnes.htsp.HtspConnection.closeConnection(HtspConnection.java:483)
                                                           at ie.macinnes.htsp.HtspConnection.run(HtspConnection.java:243)
                                                           at java.lang.Thread.run(Thread.java:818)
    02-21 10:39:57.433 17382-17415/? I/HtspConnection: Opening HTSP Connection
    02-21 10:39:57.434 17382-17412/? I/Process: Sending signal. PID: 17382 SIG: 9

**Comment by kiall** [comment]
Yea, this is where not being a native Java speaker bit me ;)

This works on the emulator, and Shield, but fails on MiBox and Sony...

It was fixed last night with:

https://github.com/kiall/android-tvheadend/commit/f532ae396ea864346fca454181447547123498e0

Which pulled in this:

https://github.com/kiall/android-htsp/commit/de024573f8b980aa06146251aeac7b3a97db45fb

Reopen if your still seeing issues with the latest build / after pulling in the latest changes!
