### ISSUE TITLE
Sony AppLink TransactionTooLargeException on banner image

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#140]
Sony 2015 sets on Android M are logging this exception every few seconds, after base64 decoding the content they give, it's part of our debug build banner image.

![image](https://cloud.githubusercontent.com/assets/52713/23299027/dddf53bc-fa77-11e6-9c1c-7ffc1626065a.png)

	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: onViewChange:componentName/json = com.sony.dtv.tvx/com.sony.dtv.tvx.tvplayer.function.actionmenu.TvMenuCardService/javascript:loaditembase64image('iVBORw0KGgoAAAANSUhEUgAACgAAAAWgCAIAAAAdYo2IAAAAA3NCSVQICAjb4U/gAAAgAElEQVR4
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: nOzdbXPjypne8bu7AZAQSZGa4z3rjY/jTZz1VhxX1klVPnm+Q14nqUrywlWbbHazdTaZsYbyEISA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: fsgLkHMooJsUZzQSH/6/QtlHN6jRkCIoai5caBX+o7yB8BZf9BVc3v3iHp0+7tG5u7z7+6L3KCT+
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: tNQXCUF8bJ8P4n3kT/NerI98inXSWHG+/8Wsk7oV6/u3b61UjVg3mLeyXuvsvlz8+O5mOcmaTDuT
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: +LsDEBFpburVnz2s7z49TtduZEUkN3IzkiLr3zIzclNIPjikjJZxLllsXmRidH+ulGRatBrMRbQW
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: NZh/3isSeTFK3f5s8FPp9HGPzt3l3V/u0enjHp2Ly7tf3KPTxz06fdyjc3d595d7dPq4R6fvte7R
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 4N/S8GUu7ykIACdvTww8vGkIkXmQ5823/+HDZove/sk8iBJRrSmqIqtGpsmUUxLOPRoCviGvvS+s
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: vWncuPW5E7M5YJQSpWR48CiJDLvbx3ckcFgCAAAAAADgwhAAAwDOUjT9DYkdYbv156lAtzfvBcCD
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: BrDzg3kQ5ZVZF6MPs+KPk1E1MjZTnqQJSPKFfVysHhdVM1+5shHjtRYR0Wqz9WglKjbfBMaxeQpH
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: JgAAAAAAAC7JqwfANGUBAAOpSz1v9iZG8UA3tqOr8w6D3i61dbFLQFsfuwS0l9bFLvXspLE78yDG
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: mqwu8o/l+OMk/zQ2NtN+cOVZACIi4rV3uW2ndXtX2UUVykbn7vMBkxnJdOTSzd1wODdKjBI9mKeC
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 5C4YjjaMAQAAXgP/VgYAAICXRgMYAHDSUk3fEOIBcIiu9Rs2Jd0e56R126B3h/XxNYBbK00rbSwA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: fmyltZsPlVejqig/zMYfJ/knur/AAS631XzV3lXybqUmTWa87MS3uZEii6z1mxnJTXyt32hgrJXo
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 6Fq/sbqwiEjsutMAAAAAAADA6SMABgCcrj2nwieD4UQzOLrWb2pNX+/FxxrAzu80g3dYt9lEtt3f
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: h7L4I91f4ICu+1tP6/W8srdVftOYketFukaLUYmmb7QBrONBr1aiYxeC7pYMTl0gmgwYAAAAAAAA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: Z4cAGACAF6O8yuti+mF2s2TdX+Cwrvu7nlfr25WUjTF+UOgFAAAAAAAAcJxXDIBZ0eS88P0CgKME
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: MdbkdVE+lDfLyZjuL7DXbvd3PauacWNyFzhfAgAAAAAAAPhqNIABAPhaKogKdH+BI+x2f5tx4+n+
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: AgAAAAAAAC/kVQJguqQAgK+Q+jEyXNNXEmv9Bjlu3l8bODy5/ZM1g4MoEdWa0arI6P4Cz+C194V9
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: nNT1vKpvK1s2IXPdKrxaRdbc7XZFzqf4glMsOCsDAAAAAAAAV4AGMADgpEXT35DYEbZbf94LdA/N
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: NwGw7/89nI/MlVdmXYw+zIo/0v0FDvOFrRer9bx6vF25cSPGay0iYpRoLXpw7oTWopXowVHVDaNz
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: FYt6Veq4jN56z+0BAAAAAACA00YAjKtBEx04AZHO7u7exCge6MZ2dHXeeKDrxQ3m1on14vxg7qV1
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: Yl3/b9Y6aeyTubEmq4v8Yzn+OMnp/gJ7dev+NtO6uavcvJKy0Zn7fMBkRnIj+eBK0JkRo8UMDqxM
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: x+dabTLjHtVlw7G5+uK4V/EGAwAAAAAAACeHABgAcBJSTd8Q4gFw8PFLN3cl3R7npHXxoLexkXlr
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: pWmljQXAj620dvOh8mpUFeWH2fjjJP9E9xc4wOW2ul2176pwt9LTpjA+7BwxuZEiiwfARSbZYG60
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: ZEayWGO4KxP3dNeRjpygEUuF5fmXiyYDBgAAAAAAwIn5xgHwNfxz2DXcRwD4xva8lCaD4UQz+Flr
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: +n6ee/GxBrDzO83gnc+ybrOJbLu/D2XxR7q/wAFd97ee1NW8crdVNmnMyPUiXWMkM5GgN9X0NXpT
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 9u1RarP15xKff/6so2xuH7Z/NAAAAAAAAHAyaAADAHA05VVeF9MPs5sl6/4Ch7ncVvNVdVutb1dS
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: Ntr4Qc4LAAAAAAAA4GV8swCYXizwrXGUAW8iiLEmr4vyobxZTsZ0f4G9fur+3lb1bdWOG525wPkS
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: AAAAAAAAwDdDAxgAgOdSQVSg+wscYbf7244bbzhdAgAAAAAAAPi2vkEATCsRAPBFUj9Ahmv6SmKt
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 3yDHzVNrA3e3/2keRIIoEdWa0arI6P4Cz+C194V9nNT1vHq8rey48ZkTEaVEq8iyuWq7xXfERBfu
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: VZK4PadqAAAAvA7+bRAAAOCt0QAGAJyE6D8RhMSOsN3681Sgm5hvAmDfnzs/mHtRXpl1MfowK/5I
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 9xc4zBe2XqzW8+rxdmXHjRivlYiIUaKV6MG5E0aL1pG5VpttOI9GwyqWLkuXI0cDY45jAAAAAAAA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: XJYXCoA5sw8AsCPS2d3dmxjFA93Yjq7OGw90vbjB3DqxXtwg6LVeWifW9eetk8Zu52Gz7m9WF/nH
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: cvxxktP9Bfby2tvcttO6uavsvAplozO3OWCCZEZyI7npf1amJdNiBgdWNxzOU4GxUpuS8XAue0rD
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: MUTDAAAAAAAAOEc0gAEAryrV9A0hHgAHH790c1fS7XFOWhcPehsbmbdWmlbaWAD82EprN3855dWo
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: KsoPs/HHSf6J7i9wgM1tdbtq31XhbqWnTWF8UD8d/LmRIpN88CY001Jkkg2CYaMlN/EA2EQbwxJv
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: DIsi/QUAAAAAAMBV+IoAmNbvpT4Cl3q/cPp47l2BPd/kZDCcaAYftaav9+JjDWDnE81gt9lExLQm
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: q4v8oSz+SPcXOKDr/j5O6vW8srdVNmnMyBl5chgbI5mR7Mim73CeujS02paAh1JXgZY9MXBqBz+z
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: AAAAAAAAcKpoAAMAkKS8yh+L6YfZzZJ1f4HDuu7vel5VtyspG238oNALAAAAAAAA4Nt6dgBMywEA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: cFWCGGvyuigfypuHyZjuL7DXbvd3PavacaMzFzhfAgAAAAAAAHh1NIABAOhTQVRQeb3t/q7o/gIH
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 7HZ/23HjDadLAAAAAAAAAG8jo9oLAHgZz/6BkrrhcE1fSaz1G+S4eWpt4O72T+ZBlIhqzWhVZA/l
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: zXIy/hPdX2Afr70rbDOp60VVzypbNj53IqKUaLVdW7f7v7D5TxVdczd9isVxJ1+oI28PAAAA7Mc/
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: nwIAgHNDAxgA8KqivziHxI6w3frzVKCbmG8CYN+fOz+YB1FemXUxej8r7un+Aoe5wtaL1XpePd6u
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 7LgR47UWETFatBL9+dyJsAlyjRatd+ZbWm224VwpUYO5isfIoiQx5zgGAAAAAADAdSAA/iKc93de
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: +H7hNF3EMzPa2Y3955NRPNCN7ejqvPFA14sbzK0T68UNgl7rpXViXX/eOmnszjyIsSari/xjOV5O
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: crq/wF7dur/ttG7uKjevpGxM5sx2b24kzyT//PH2gM3MZusxWowRMzjgjg2MlRJ1ZNxLNCxyIT+V
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: AAAAAAAAIATAAIBvJNX0DSEeAAcfv3RzV9LtcU5aFw96GxuZt1aaVtpYAPzYSms3HyqvRlVRvp+N
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: l5P8E91f4IBu3d/2XRXuVnraFMaHnSMmMzLaDYBl87qQGSl6cxERMVqKWACstWSxAFhJPAAWtcmA
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: h54/BAAAAAAAAM4XATAA4OXtKZIlg+FEM/ioNX29Fx9rADufaAa7zSay7f4+lMU93V/ggK77+zip
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: 1/PK3lbZpDEj14t0nzR9d47WTEumk03fSACcavpK/NLQn3dFpeJeLhANAAAAAACAi0EADACAKK/y
	02-24 09:49:54.892  4232  4349 I TvDotActionExtensionProvider: uph+mN0sWfcXOKzr/q7nVXW7krLRxg8KvQAAAAAAAADeBgHw
	02-24 09:49:54.895  4232  4349 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 679116)
	02-24 09:49:54.896  4232  4349 W System.err: android.os.TransactionTooLargeException: data parcel size 679116 bytes
	02-24 09:49:54.897  4232  4349 W System.err: 	at android.os.BinderProxy.transactNative(Native Method)
	02-24 09:49:54.897  4232  4349 W System.err: 	at android.os.BinderProxy.transact(Binder.java:503)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.scrums.action.libtvdotactionextension.ITvDotActionExtensionViewChangeCallback$Stub$Proxy.onViewChange(ITvDotActionExtensionViewChangeCallback.java:98)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.scrums.action.libtvdotactionextension.TvDotActionExtensionProvider$1.onViewChanged(TvDotActionExtensionProvider.java:52)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.scrums.action.libtvdotactionextension.TvDotActionExtensionViewChangeSubject.notify(TvDotActionExtensionViewChangeSubject.java:44)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.scrums.action.libtvdotactionextension.TvDotActionExtensionManager.sendViewChange(TvDotActionExtensionManager.java:37)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.tvcardstate.AppLinkItemCreator.updateAppLinkItemWebView(AppLinkItemCreator.java:65)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.tvcardstate.AppLinkItemCreator.makeStateOfAppLink(AppLinkItemCreator.java:59)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.tvcardstate.VirtualTunerState.makeStateOfAppLink(VirtualTunerState.java:77)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.tvcardstate.VirtualTunerState.getItems(VirtualTunerState.java:39)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.ActionItemUpdater$ActionItemUpdateTask.doInBackground(ActionItemUpdater.java:108)
	02-24 09:49:54.897  4232  4349 W System.err: 	at com.sony.dtv.tvx.tvplayer.function.actionmenu.ActionItemUpdater$ActionItemUpdateTask.doInBackground(ActionItemUpdater.java:91)
	02-24 09:49:54.897  4232  4349 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	02-24 09:49:54.898  4232  4349 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	02-24 09:49:54.898  4232  4349 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	02-24 09:49:54.898  4232  4349 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	02-24 09:49:54.900  4232  4349 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	02-24 09:49:54.900  4232  4349 W System.err: 	at java.lang.Thread.run(Thread.java:818)

**Comment by kiall** [comment]
(I'm running a debug build, it's possible this doesn't affect non-debug builds - or that it fails with the b64 content the non-debug banner)
